project:
  type: book

book:
  title: "Mastering R by Examples"
  author: "Avan Suinesiaputra"
  date: ""
  chapters:
    - index.qmd
    - pipes.qmd
    - load_and_prepare.qmd
    - data_summary.qmd
    - bland_altman.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto

